# paths are relative to the project's root

rotor_path: "rotor"
examples_dir: "examples/symbolic"
models_dir: "models"

base_dirs:
  starc: "starc"
  gcc: "gcc"

output_dir: "models"
default_output: &default_output ""



models:
  starc:
    64bit:
      riscv: 
        # btor2:
        #   command: "{rotor} -c {source_file} - 1 -o {output}"
        #   example_output: "starc/64-bit/riscv/btor2"
        #   output: *default_output

        smt: 
          command: "{rotor} -c {source_file}  - 1 -k -smt -nocomments -o {output}"
          example_output: "starc/64-bit/riscv/smt"
          output: *default_output
      
  #     riscu:
  #       btor2:
  #         command: "{rotor} -c {source_file} - 1 -riscuonly -o {output}"
  #         output: *default_output
  #         example_output: "starc/64-bit/riscu/btor2"
  #
  #       smt: 
  #         command: "{rotor} -c {source_file} - 1 -riscuonly -k -smt -nocomments -o {output}"
  #         output: *default_output
  #         example_output: "starc/64-bit/riscu/smt"
  #
  #   32bit:
  #     riscv:
  #       btor2: 
  #         command: "{rotor} -m32 -c {source_file} - 1 -o {output}"
  #         output: *default_output
  #         example_output: "starc/32-bit/riscv/btor2"
  #
  #       smt: 
  #         command: "{rotor} -m32 -c {source_file} - 1 -k -smt -nocomments -o {output}"
  #         output: *default_output
  #         example_output: "starc/32-bit/riscv/smt"
  #     
  #     riscu:
  #       btor2: 
  #         command: "{rotor} -m32 -c {source_file} - 1 -riscuonly -o {output}"
  #         output: *default_output
  #         example_output: "starc/32-bit/riscu/btor2"
  #
  #       smt: 
  #         command: "{rotor} -m32 -c {source_file} - 1 -k -smt -nocomments -o {output}"
  #         output: *default_output
  #         example_output: "starc/32-bit/riscu/smt"
  # gcc:
  #
  #   rv64imac:
  #     compilation: "riscv64-unknown-elf-gcc -mabi=lp64 -march=rv64imac -Wall -Wextra -D'uint64_t=unsigned long' {source_file} -o {output_machine_code}"
  #     
  #     btor2: 
  #       command: "{rotor} -l {source_file} - 1 -o {output}"
  #       output: *default_output
  #       example_output: "gcc/rv64imac/btor2"
  #
  #     smt: 
  #       command: "{rotor} -l {source_file} - 1 -k -smt -nocomments -o {output}"
  #       output: *default_output
  #       example_output: "gcc/rv64imac/smt"
  #
  #   rv32imac:
  #     compilation: "riscv64-unknown-elf-gcc -mabi=ilp32 -march=rv32imac -Wall -Wextra -D'uint64_t=unsigned long' {source_file} -o {output_machine_code}" 
  #
  #     btor2: 
  #       command: "{rotor} -l {source_file} - 1 -o {output}"
  #       output: *default_output
  #       example_output: "gcc/rv32imac/btor2"
  #
  #     smt: 
  #       command: "{rotor} -l {source_file} - 1 -k -smt -nocomments -o {output}"
  #       output: *default_output
  #       example_output: "gcc/rv32imac/smt"
  #
  #   rv32im:
  #     compilation: "riscv64-unknown-elf-gcc -mabi=ilp32 -march=rv32im -Wall -Wextra -D'uint64_t=unsigned long' {source_file} -o {output_machine_code}"
  #     
  #     fullriscv:
  #       
  #       btor2: 
  #         command: "{rotor} -l {source_file} - 1 -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32im/fullriscv/btor2"
  #
  #       smt: 
  #         command: "{rotor} -l {source_file} - 1 -k -smt -nocomments -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32im/fullriscv/smt"
  #
  #     nocompressed:
  #
  #       btor2: 
  #         command: "{rotor} -l {source_file} - 1 -noRVC -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32im/fullriscv/btor2"
  #
  #       smt: 
  #         command: "{rotor} -l {source_file} - 1 -noRVC -k -smt -nocomments -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32im/nocompressed/smt"
  #   
  #   rv32i:
  #     compilation: "riscv64-unknown-elf-gcc -mabi=ilp32 -march=rv32i -Wall -Wextra -D'uint64_t=unsigned long' {source_file} -o {output_machine_code}"
  #     
  #     fullriscv:
  #
  #       btor2:
  #         command: "{rotor} -l {source_file} - 1 -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32i/fullriscv/btor2"
  #
  #       smt: 
  #         command: "{rotor} -l {source_file} - 1 -k -smt -nocomments -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32i/fullriscv/smt"
  #
  #     nocompressed:
  #     
  #       btor2: 
  #         command: "{rotor} -l {source_file} - 1 -noRVC -noRVM -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32i/nocompressed/btor2"
  #
  #       smt: 
  #         command: "{rotor} -l {source_file} - 1 -noRVC -noRVM -k -smt -nocomments -o {output}"
  #         output: *default_output
  #         example_output: "gcc/rv32i/nocompressed/smt"
  #
