name: Deploy Docker Selfie

# only triggers on default branch when "Make Everything Selfie" succeeded
on:
  workflow_run:
    workflows: ["Make Everything Selfie"]
    types: [completed]

jobs:
  deploy-selfie-on-docker:
    name: Deploy selfie on docker
    runs-on: ubuntu-latest
    environment: docker
    # requires DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD secrets from docker environment
    # see github repository's Settings -> Environments

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t cksystemsteaching/selfie .
    - name: Deploy docker image
      run: |
        echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push cksystemsteaching/selfie
      if: ${{ github.event_name == 'push' && github.repository == 'cksystemsteaching/selfie' }}