name: Run Docker Selfie

on:
  push:
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  schedule:
    # trigger fridays at 12am
    - cron: '0 0 * * 5'

jobs:
  selfie-on-docker:
    name: Build, test, and deploy selfie on docker
    runs-on: ubuntu-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Build docker image
      run: docker build -t cksystemsteaching/selfie .
    - name: Test selfie in docker image
      run: |
        docker run cksystemsteaching/selfie make -j -O everything
        docker run cksystemsteaching/selfie make pythons
    - name: Deploy docker image
      environment: docker
      # requires DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD secrets from docker environment
      # see github repository's Settings -> Environments
      run: |
        echo '${{ secrets.DOCKERHUB_PASSWORD }}' | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push cksystemsteaching/selfie
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'cksystemsteaching/selfie' }}