name: Make Everything Selfie

on:
  push:
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  pull_request:
    paths-ignore:
    - '**.md'
    - '**.txt'
    - 'docs'
    - 'AUTHORS'
    - 'LICENSE'
  schedule:
    # trigger fridays at 12am
    - cron: '0 0 * * 5'

jobs:
  make-all-of-selfie-on-linux:
    name: Make all of selfie on Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      run: make -j -O all
    - name: Use Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    - name: Run autograder baseline
      run: make grade

  make-all-of-selfie-on-macos:
    name: Make all of selfie on macOS
    runs-on: macos-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      run: make -j all
    - name: Use Python 3.7.x
      uses: actions/setup-python@v1
      with:
        python-version: "3.7.x"
    - name: Run autograder baseline
      run: make grade

  make-all-of-selfie-on-windows:
    name: Make all of selfie on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout selfie
      uses: actions/checkout@v2
    - name: Make all
      env:
        CC: gcc
      run: make -j -O all
    # python3 does not work here